// Generated by CoffeeScript 1.4.0
(function() {
  var food, square;

  square = function(x) {
    if (x == null) {
      x = 5;
    }
    return x * x;
  };

  log(square(4));

  food = {
    fruit: {
      name: "apple",
      price: 1.5
    },
    fruit: {
      name: "orange",
      price: 2.0
    },
    veggie: {
      name: "carrot",
      price: "1.2"
    }
  };

}).call(this);
